#pragma once

#define WINDOW_WIDTH 800
#define WINDOW_HEGITH 600

#define WINDOW_WIDTH_TP 810
#define WINDOW_HEGITH_TP 610


#define LINEAR_DRAG 1.2f
#define ANGULAR_DRAG 6.0f

#define SHIP_LIN_ACC_FACTOR 500
#define SHIP_ANG_ACC_FACTOR 180000

#define ASTEROID_LIN_ACC_FACTOR 150
#define ASTEROID_ANG_ACC_FACTOR 160000

#define ASTEROID_SPAWN_RATIO 0.2

#define ASTEROID_BIG_POINTS 50
#define ASTEROID_MEDIUM_POINTS 30
#define ASTEROID_SMALL_POINTS 20